#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon May 11 22:52:13 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
